# Generated by Django 3.0.4 on 2021-10-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_iva', models.IntegerField()),
                ('precio_sin_iva', models.IntegerField()),
                ('Cantidad_ticket', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Categoria')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Ticket')),
            ],
        ),
    ]
