# Generated by Django 3.0.6 on 2021-10-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.bd')),
            ],
        ),
        migrations.AddField(
            model_name='bd',
            name='prueba_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.guia'),
        ),
    ]
