# Generated by Django 3.0.6 on 2021-10-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_guia_pru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='bd',
        ),
        migrations.DeleteModel(
            name='guia',
        ),
    ]
