# Generated by Django 3.0.6 on 2021-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_auto_20211023_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace',
            options={'verbose_name': 't^n = n!/sn^1', 'verbose_name_plural': 't^n = n!/sn^1'},
        ),
        migrations.RemoveField(
            model_name='laplace_2',
            name='variable_1',
        ),
        migrations.AddField(
            model_name='laplace',
            name='denominador',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='laplace',
            name='numerador',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='laplace',
            name='tota',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='laplace',
            name='var3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laplace',
            name='var_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laplace',
            name='var_s_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laplace',
            name='var_s_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laplace_2',
            name='var_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laplace',
            name='var_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
