# Generated by Django 3.0.6 on 2021-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_auto_20211023_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='laplace_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='laplace_2',
            name='var_1',
        ),
        migrations.AddField(
            model_name='laplace_2',
            name='variable_1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
