# Generated by Django 3.0.6 on 2021-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_auto_20211023_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laplace_2',
            name='variable_1',
            field=models.IntegerField(),
        ),
    ]
