# Generated by Django 3.0.6 on 2021-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0008_auto_20211023_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace_2',
            options={'verbose_name': 'a/s', 'verbose_name_plural': 'a/s'},
        ),
        migrations.AddField(
            model_name='laplace_2',
            name='resultado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
