# Generated by Django 3.0.6 on 2021-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0009_auto_20211023_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laplace_2',
            name='resultado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
