# Generated by Django 3.0.6 on 2021-10-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0010_auto_20211023_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='laplace_3',
        ),
        migrations.AlterModelOptions(
            name='laplace_2',
            options={},
        ),
    ]
