# Generated by Django 3.0.6 on 2021-10-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0011_auto_20211023_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace',
            options={},
        ),
    ]
