# Generated by Django 3.0.6 on 2021-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0012_auto_20211023_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='laplace_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField()),
                ('resultado', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='laplace',
            options={'verbose_name': 't^n = n!/sn^1', 'verbose_name_plural': 't^n = n!/sn^1'},
        ),
        migrations.AlterModelOptions(
            name='laplace_2',
            options={'verbose_name': 'a/s', 'verbose_name_plural': 'a/s'},
        ),
    ]
