# Generated by Django 3.0.4 on 2021-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0014_auto_20211023_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='laplace_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField()),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
