# Generated by Django 3.0.4 on 2021-10-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0015_laplace_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace',
            options={'verbose_name': 't^n = n!/sn^1', 'verbose_name_plural': 't^n = n!/sn^+1'},
        ),
        migrations.AlterModelOptions(
            name='laplace_4',
            options={'verbose_name': 'e^t senb+', 'verbose_name_plural': 'e^t senb+'},
        ),
    ]
