# Generated by Django 3.0.4 on 2021-10-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0017_laplace_4_var_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace_4',
            options={},
        ),
    ]
