# Generated by Django 3.0.4 on 2021-10-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0018_auto_20211024_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace_4',
            options={'verbose_name': 'e^t cosb+', 'verbose_name_plural': 'e^t cosb+'},
        ),
    ]
