# Generated by Django 3.0.4 on 2021-10-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0019_auto_20211024_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='laplace_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField()),
                ('var_2', models.IntegerField()),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'e^t cosb+',
                'verbose_name_plural': 'e^t cosb+',
            },
        ),
        migrations.AlterModelOptions(
            name='laplace_4',
            options={'verbose_name': 'e^t senb+', 'verbose_name_plural': 'e^t senb+'},
        ),
    ]
