# Generated by Django 3.0.4 on 2021-10-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0020_auto_20211024_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='laplace_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField()),
                ('var_2', models.IntegerField()),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='laplace_5',
            options={},
        ),
    ]
