# Generated by Django 3.0.4 on 2021-10-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0021_auto_20211024_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace_5',
            options={'verbose_name': 'e^t cosb+', 'verbose_name_plural': 'e^t cosb+'},
        ),
        migrations.AlterModelOptions(
            name='laplace_6',
            options={'verbose_name': 's^2+a^2', 'verbose_name_plural': 's^2+a^2'},
        ),
    ]
