# Generated by Django 3.0.4 on 2021-10-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0022_auto_20211024_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laplace_6',
            name='var_2',
        ),
    ]
