# Generated by Django 3.0.4 on 2021-10-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0023_remove_laplace_6_var_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='laplace_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField()),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='laplace_6',
            options={'verbose_name': 'a/s^2+a^2', 'verbose_name_plural': 'a/s^2+a^2'},
        ),
    ]
