# Generated by Django 3.0.4 on 2021-10-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0024_auto_20211024_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace_7',
            options={'verbose_name': 'cos at', 'verbose_name_plural': 'cos at'},
        ),
    ]
