# Generated by Django 3.0.4 on 2021-10-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0025_auto_20211024_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laplace_7',
            options={'verbose_name': 'cos at = s/s^4 a^2', 'verbose_name_plural': 'cos at = s/s^4 a^2'},
        ),
    ]
